import type { Camp } from '../types';

export const camp: Camp[] = [
  {
    id: 1,
    name: 'Adonis Yellow Camp',
    member: [1, 2, 3, 4],
    capacity: 10,
    image: './adonis-yellow-16x9.webp',
    location_id: 1,
    provider_id: 1,
  },
  {
    id: 2,
    name: 'Camellia Rose Camp',
    member: [1, 2, 3, 4],
    capacity: 10,
    image: './camellia-rose-16x9.webp',
    location_id: 2,
    provider_id: 2,
  },
  {
    id: 3,
    name: 'Clean Pool Camp',
    member: [1, 2, 3, 4],
    capacity: 10,
    image: './clean-pool-16x9.webp',
    location_id: 3,
    provider_id: 3,
  },
  {
    id: 4,
    name: 'Lima Green Camp',
    member: [1, 2, 3, 4],
    capacity: 10,
    image: './lima-green-16x9.webp',
    location_id: 4,
    provider_id: 4,
  },
  {
    id: 5,
    name: 'Majorelle Blue Camp',
    member: [1, 2, 3, 4],
    capacity: 10,
    image: './majorelle-blue-16x9.webp',
    location_id: 5,
    provider_id: 5,
  },
  {
    id: 6,
    name: 'Navy Purple Camp',
    member: [1, 2, 3, 4],
    capacity: 10,
    image: './navy-purple-16x9.webp',
    location_id: 6,
    provider_id: 6,
  },
  {
    id: 7,
    name: 'Orion Pink Camp',
    member: [1, 2, 3, 4],
    capacity: 10,
    image: './orion-pink-16x9.webp',
    location_id: 7,
    provider_id: 7,
  },
  {
    id: 8,
    name: 'Weird Green Camp',
    member: [1, 2, 3, 4],
    capacity: 10,
    image: './weird-green-16x9.webp',
    location_id: 8,
    provider_id: 8,
  },
  {
    id: 9,
    name: 'Zany Pink Camp',
    member: [1, 2, 3, 4],
    capacity: 10,
    image: './zany-pink-16x9.webp',
    location_id: 9,
    provider_id: 9,
  },
];
