import type { Location } from '../types';

export const location: Location[] = [
  {
    id: 1,
    type: 'Course',
    name: 'Vocabulary Master',
    images: ['./majorelle-blue-4x3.webp', './majorelle-blue-16x9.webp', './majorelle-blue-21x9.webp'],
    maps_id: 'YVCoqqC4YqS8DxTT6',
    provider_id: 5,
  },
  {
    id: 2,
    type: 'Course',
    name: 'Writing Master',
    images: ['./majorelle-blue-4x3.webp', './majorelle-blue-16x9.webp', './majorelle-blue-21x9.webp'],
    maps_id: 'YVCoqqC4YqS8DxTT6',
    provider_id: 5,
  },
  {
    id: 3,
    type: 'Course',
    name: 'Idoms and Expressions Center',
    images: ['./orion-pink-4x3.webp', './orion-pink-16x9.webp', './orion-pink-21x9.webp'],
    maps_id: 'YVCoqqC4YqS8DxTT6',
    provider_id: 7,
  },
  {
    id: 4,
    type: 'Course',
    name: 'Listening Center',
    images: ['./orion-pink-4x3.webp', './orion-pink-16x9.webp', './orion-pink-21x9.webp'],
    maps_id: 'YVCoqqC4YqS8DxTT6',
    provider_id: 7,
  },
  {
    id: 5,
    type: 'Course',
    name: 'Pronunciation Labs',
    images: ['./camellia-rose-4x3.webp', './camellia-rose-16x9.webp', './camellia-rose-21x9.webp'],
    maps_id: 'YVCoqqC4YqS8DxTT6',
    provider_id: 2,
  },
  {
    id: 6,
    type: 'Course',
    name: 'Speaking Labs',
    images: ['./camellia-rose-4x3.webp', './camellia-rose-16x9.webp', './camellia-rose-21x9.webp'],
    maps_id: 'YVCoqqC4YqS8DxTT6',
    provider_id: 2,
  },
  {
    id: 7,
    type: 'Course',
    name: 'Phrasal Room',
    images: ['./adonis-yellow-4x3.webp', './adonis-yellow-16x9.webp', './adonis-yellow-21x9.webp'],
    maps_id: 'YVCoqqC4YqS8DxTT6',
    provider_id: 1,
  },
  {
    id: 8,
    type: 'Course',
    name: 'Reading Room',
    images: ['./adonis-yellow-4x3.webp', './adonis-yellow-16x9.webp', './adonis-yellow-21x9.webp'],
    maps_id: 'YVCoqqC4YqS8DxTT6',
    provider_id: 1,
  },
];
