import type { District } from '../types';

export const district: District[] = [
  {
    iso: 'ID-AC',
    name: 'Aceh',
    city: ['Banda Aceh', 'Langsa', 'Lhokseuwame', 'Sabang', 'Subulussalam'],
    regency: [
      'Aceh Barat',
      'Aceh Barat Daya',
      'Aceh Besar',
      'Aceh Jaya',
      'Aceh Selatan',
      'Aceh Singkil',
      'Aceh Tamiang',
      'Aceh Tengah',
      'Aceh Tenggara',
      'Aceh Timur',
      'Aceh Utara',
      'Bener Meriah',
      'Biruen',
      'Gayo Lues',
      'Nagan Raya',
      'Pidie',
      'Pidie Jaya',
      'Simeulue',
    ],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-BT',
    name: 'Banten',
    city: ['Cilegon', 'Serang', 'Tanggerang', 'Tanggerang Selatan'],
    regency: ['Lebak', 'Pandeglang', 'Serang', 'Tangerang'],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-BE',
    name: 'Bengkulu',
    city: ['Bengkulu'],
    regency: ['Bengkulu Selatan', 'Bengkulu Tengah', 'Bengkulu Utara', 'Kaur', 'Kepahiang', 'Lebong', 'Mukomuko', 'Rejang Lebong', 'Seluma'],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-JK',
    name: 'Jakarta',
    city: ['Jakarta Barat', 'Jakarta Pusat', 'Jakarta Selatan', 'Jakarta Timur', 'Jakarta Utara'],
    regency: ['Kepulauan Seribu'],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-JA',
    name: 'Jambi',
    city: ['Jambi', 'Sungai Penuh'],
    regency: ['Batang Hari', 'Bungo', 'Kerinci', 'Merangin', 'Muaro Jambi', 'Sarolangun', 'Tanjung Jabung Barat', 'Tanjung Jabung Timur', 'Tebo'],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-JB',
    name: 'Jawa Barat',
    city: ['Bandung', 'Banjar', 'Bekasi', 'Bogor', 'Cimahi', 'Cirebon', 'Depok', 'Sukabumi', 'Tasikmalaya'],
    regency: [
      'Bandung',
      'Bandung Barat',
      'Bekasi',
      'Bogor',
      'Ciamis',
      'Cianjur',
      'Cirebon',
      'Garut',
      'Indramayu',
      'Karawang',
      'Kuningan',
      'Majalengka',
      'Pangandaran',
      'Purwakarta',
      'Subang',
      'Sukabumi',
      'Sumedang',
      'Tasikmalaya',
    ],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-JT',
    name: 'Jawa Tengah',
    city: ['Magelang', 'Pekalongan', 'Salatiga', 'Semarang', 'Surakarta', 'Tegal'],
    regency: [
      'Banjarnegara',
      'Banyumas',
      'Batang',
      'Blora',
      'Boyolali',
      'Brebes',
      'Cilacap',
      'Demak',
      'Grobogan',
      'Jepara',
      'Karanganyar',
      'Kebumen',
      'Kendal',
      'Klaten',
      'Kudus',
      'Magelang',
      'Pati',
      'Pekalongan',
      'Pemalang',
      'Purbalingga',
      'Purworejo',
      'Rembang',
      'Semarang',
      'Seragen',
      'Sukoharjo',
      'Tegal',
      'Temanggung',
      'Wonogiri',
      'Wonosobo',
    ],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-JI',
    name: 'Jawa Timur',
    city: ['Batu', 'Blitar', 'Kediri', 'Madiun', 'Malang', 'Mojokerto', 'Pasuruan', 'Probolinggo', 'Surabaya'],
    regency: [
      'Bangkalan',
      'Banyuwangi',
      'Blitar',
      'Bojonegoro',
      'Bondowoso',
      'Gresik',
      'Jember',
      'Jombang',
      'Kediri',
      'Lamongan',
      'Lumajang',
      'Madiun',
      'Magetan',
      'Malang',
      'Mojokerto',
      'Nganjuk',
      'Ngawi',
      'Pacitan',
      'Pamekasan',
      'Pasuruan',
      'Ponorogo',
      'Probolinggo',
      'Sampang',
      'Situbondo',
      'Sumenep',
      'Trenggalek',
      'Tuban',
      'Tulungagung',
    ],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-KB',
    name: 'Kalimantan Barat',
    city: ['Pontianak', 'Singkawang'],
    regency: [
      'Bengkayang',
      'Kapuas Hulu',
      'Kayong Utara',
      'Ketapang',
      'Kubu Raya',
      'Landak',
      'Melawi',
      'Mempawah',
      'Sambas',
      'Sanggau',
      'Sekadau',
      'Sintang',
    ],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-KT',
    name: 'Kalimantan Tengah',
    city: ['Palangka Raya'],
    regency: [
      'Barito Selatan',
      'Barito Timur',
      'Barito Utara',
      'Gunung Mas',
      'Kapuas',
      'Katingan',
      'Kotawaringin Barat',
      'Kotawaringin Timur',
      'Lamandau',
      'Murung Raya',
      'Pulang Pisau',
      'Seruyan',
      'Sukamara',
    ],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-BB',
    name: 'Kepulauan Bangka Belitung',
    city: ['Pangkal Pinang'],
    regency: ['Bangka', 'Bangka Barat', 'Bangka Selatan', 'Bangka Tengah', 'Belitung', 'Belitung Timur'],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-KR',
    name: 'Kepulauan Riau',
    city: ['Batam', 'Tanjung Pinang'],
    regency: ['Bintan', 'Karimun', 'Kepulauan Anambas', 'Lingga', 'Natuna'],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-LA',
    name: 'Lampung',
    city: ['Bandar Lampung', 'Metro'],
    regency: [
      'Lampung Barat',
      'Lampung Selatan',
      'Lampung Tengah',
      'Lampung Timur',
      'Lampung Utara',
      'Mesuji',
      'Pesawaran',
      'Pesisir Barat',
      'Pringsewu',
      'Tanggamus',
      'Tulang Bawang',
      'Tulang Bawang Barat',
      'Way Kanan',
    ],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-RI',
    name: 'Riau',
    city: ['Dumai', 'Pekanbaru'],
    regency: [
      'Bengkalis',
      'Indragiri Hilir',
      'Indragiri Hulu',
      'Kampar',
      'Kepulauan Meranti',
      'Kuantan Singingi',
      'Pelalawan',
      'Rokan Hilir',
      'Rokan Hulu',
      'Siak',
    ],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-SB',
    name: 'Sumatera Barat',
    city: ['Bukit Tinggi', 'Padang', 'Padang Panjang', 'Pariaman', 'Payakumbuh', 'Sawahlunto', 'Solok'],
    regency: [
      'Agam',
      'Dharmasraya',
      'Kepulauan Mentawai',
      'Lima Puluh Kota',
      'Padang Pariaman',
      'Pasaman',
      'Pasaman Barat',
      'Pesisir Selatan',
      'Sijunjung',
      'Solok',
      'Solok Selatan',
      'Tanah Datar',
    ],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-SS',
    name: 'Sumatera Selatan',
    city: ['Lubuklinggau', 'Pagar Alam', 'Palembang', 'Prabumulih'],
    regency: [
      'Banyuasin',
      'Empat Lawang',
      'Lahat',
      'Muara Enim',
      'Musi Banyuasin',
      'Musi Rawas',
      'Musi Rawas Utara',
      'Ogan Ilir',
      'Ogan Komering Ilir',
      'Ogan Komering Ulu',
      'Ogan Komering Ulu Selatan',
      'Ogan Komering Ulu Timur',
      'Penukal Abab Lematang Ilir',
    ],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-SU',
    name: 'Sumatera Utara',
    city: ['Binjai', 'Gunungsitoli', 'Medan', 'Padang Sidempuan', 'Pematang Siantar', 'Sibolga', 'Tanjung Balai', 'Tebing Tinggi'],
    regency: [
      'Asahan',
      'Batubara',
      'Dairi',
      'Deli Serdang',
      'Humbang Hasundutan',
      'Karo',
      'Labuhan Batu',
      'Labuhan Batu Selatan',
      'Labuhan Batu Utara',
      'Labuhan Batu Utara',
      'Langkat',
      'Mandailing Natal',
      'Nias',
      'Nias',
      'Nias Barat',
      'Nias Selatan',
      'Nias Utara',
      'Nias Utara',
      'Padang Lawas',
      'Padang Lawas Utara',
      'Pakpak Bharat',
      'Samosir',
      'Serdang Bedagai',
      'Simalungun',
      'Tapanuli Selatan',
      'Tapanuli Tengah',
      'Tapanuli Utara',
      'Toba',
    ],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-YO',
    name: 'Yogyakarta',
    city: ['Yogyakarta'],
    regency: ['Bantul', 'Gunung Kidul', 'Kulon Progo', 'Sleman'],
    timezone: 'UTC+7',
  },
  {
    iso: 'ID-BA',
    name: 'Bali',
    city: ['Denpasar'],
    regency: ['Badung', 'Bangli', 'Buleleng', 'Gianyar', 'Jembrana', 'Karangasem', 'Klungkung', 'Tabanan'],
    timezone: 'UTC+8',
  },
  {
    iso: 'ID-GO',
    name: 'Gorontalo',
    city: ['Gorontalo'],
    regency: ['Boalemo', 'Bone Bolango', 'Gorontalo', 'Gorontalo Utara', 'Pohuwato'],
    timezone: 'UTC+8',
  },
  {
    iso: 'ID-KS',
    name: 'Kalimantan Selatan',
    city: ['Banjarbaru', 'Banjarmasin'],
    regency: [
      'Balangan',
      'Banjar',
      'Barito Kuala',
      'Hulu Sungai Selatan',
      'Hulu Sungai Tengah',
      'Hulu Sungai Utara',
      'Kotabaru',
      'Tabalong',
      'Tanah Bumbu',
      'Tanah Laut',
      'Tapin',
    ],
    timezone: 'UTC+8',
  },
  {
    iso: 'ID-KI',
    name: 'Kalimantan Timur',
    city: ['Balikpapan', 'Bontang', 'Samarinda'],
    regency: ['Berau', 'Kutai Barat', 'Kutai Kartanegara', 'Kutai Timur', 'Mahakam Ulu', 'Paser', 'Penajam North Paser'],
    timezone: 'UTC+8',
  },
  {
    iso: 'ID-KU',
    name: 'Kalimantan Utara',
    city: ['Tarakan'],
    regency: ['Bulungan', 'Malinau', 'Nunukan', 'Tana Tidung'],
    timezone: 'UTC+8',
  },
  {
    iso: 'ID-NB',
    name: 'Nusa Tenggara Barat',
    city: ['Bima', 'Mataram'],
    regency: ['Bima', 'Dompu', 'Lombok Barat', 'Lombok Tengah', 'Lombok Timur', 'Lombok Utara', 'Sumbawa', 'Sumbawa Barat'],
    timezone: 'UTC+8',
  },
  {
    iso: 'ID-NT',
    name: 'Nusa Tenggara Timur',
    city: ['Kupang'],
    regency: [
      'Alor',
      'Belu',
      'Ende',
      'Flores Timur',
      'Kupang',
      'Lembata',
      'Malaka',
      'Manggarai',
      'Manggarai Barat',
      'Manggarai Timur',
      'Nagekeo',
      'Ngada',
      'Rote Ndao',
      'Sabi Raijua',
      'Sikka',
      'Sumba Barat',
      'Sumba Barat Daya',
      'Sumba Tengah',
      'Sumba Timur',
      'Timor Tengah Selatan',
      'Timor Tengah Utara',
    ],
    timezone: 'UTC+8',
  },
  {
    iso: 'ID-SR',
    name: 'Sulawesi Barat',
    city: [],
    regency: ['Majene', 'Mamasa', 'Mamuju', 'Mamuju Tengah', 'Pasangkayu', 'Polewali Mandar'],
    timezone: 'UTC+8',
  },
  {
    iso: 'ID-SN',
    name: 'Sulawesi Selatan',
    city: ['Makassar', 'Palopo', 'Parepare'],
    regency: [
      'Bantaeng',
      'Barru',
      'Bone',
      'Bulukumba',
      'Enrekang',
      'Gowa',
      'Janeponto',
      'Kepulauan Selayar',
      'Luwu',
      'Luwu Timur',
      'Luwu Utara',
      'Maros',
      'Pangkajene dan Kepulauan',
      'Pinrang',
      'Sidenreng Rappang',
      'Sinjai',
      'Soppeng',
      'Takalar',
      'Tana Toraja',
      'Toraja Utara',
      'Wajo',
    ],
    timezone: 'UTC+8',
  },
  {
    iso: 'ID-ST',
    name: 'Sulawesi Tengah',
    city: ['Palu'],
    regency: [
      'Banggai',
      'Banggai Laut',
      'Buol',
      'Donggala',
      'Kepulauan Banggai',
      'Morowali',
      'Morowali Utara',
      'Parigi Moutong',
      'Poso',
      'Sigi',
      'Tojo Una-Una',
      'Tolitoli',
    ],
    timezone: 'UTC+8',
  },
  {
    iso: 'ID-SG',
    name: 'Sulawesi Tenggara',
    city: ['Baubau', 'Kendari'],
    regency: [
      'Bombana',
      'Buton',
      'Buton Selatan',
      'Buton Tengah',
      'Buton Utara',
      'Kepulauan Konawe',
      'Kolaka',
      'Kolaka Timur',
      'Kolaka Utara',
      'Konawe',
      'Konawe Selatan',
      'Konawe Utara',
      'Muna',
      'Muna Barat',
      'Wakatobi',
    ],
    timezone: 'UTC+8',
  },
  {
    iso: 'ID-SA',
    name: 'Sulawesi Utara',
    city: ['Bitung', 'Kotamobagu', 'Manado', 'Tomohon'],
    regency: [
      'Bolaang Mongondow',
      'Boolaang Mongondow Utara',
      'Boolang Mongondow Selatan',
      'Boolang Mongondow Timur',
      'Kepulauan Sangihe',
      'Kepulauan Sitaro',
      'Kepulauan Talaud',
      'Minahasa',
      'Minahasa Selatan',
      'Minahasa Tenggara',
      'Minahasa Utara',
    ],
    timezone: 'UTC+8',
  },
  {
    iso: 'ID-MA',
    name: 'Maluku',
    city: ['Ambon', 'Tual'],
    regency: [
      'Buru',
      'Buru Selatan',
      'Kepulauan Aru',
      'Kepulauan Tanimbar',
      'Maluku Barat Daya',
      'Maluku Tengah',
      'Maluku Tenggara',
      'Seram Barat',
      'Seram Timur',
    ],
    timezone: 'UTC+9',
  },
  {
    iso: 'ID-MU',
    name: 'Maluku Utara',
    city: ['Ternate', 'Tidore'],
    regency: [
      'Halmahera Barat',
      'Halmahera Selatan',
      'Halmahera Tengah',
      'Halmahera Timur',
      'Halmahera Utara',
      'Kepulauan Morotai',
      'Kepulauan Sula',
      'Pulau Taliabu',
    ],
    timezone: 'UTC+9',
  },
  {
    iso: 'ID-PA',
    name: 'Papua',
    city: ['Jayapura'],
    regency: ['Biak Numfor', 'Jayapura', 'Keerom', 'Kepulauan Yarpen', 'Mamberamo Raya', 'Sarmi', 'Supiori', 'Waropen'],
    timezone: 'UTC+9',
  },
  {
    iso: 'ID-PB',
    name: 'Papua Barat',
    city: [],
    regency: ['Fakfak', 'Kaimana', 'Manokwari', 'Manokwari Selatan', 'Pegunungan Arfak', 'Teluk Bintuni', 'Teluk Wondama'],
    timezone: 'UTC+9',
  },
  {
    iso: 'ID-PD',
    name: 'Papua Barat Daya',
    city: ['Sorong'],
    regency: ['Maybrat', 'Raja Ampat', 'Sorong', 'Sorong Selatan', 'Tambrauw'],
    timezone: 'UTC+9',
  },
  {
    iso: 'ID-PE',
    name: 'Papua Pegunungan',
    city: [],
    regency: ['Jayawijaya', 'Lanny Jaya', 'Mamberamo Tengah', 'Nduga', 'Pegunungan Bintang', 'Tolikara', 'Yahukimo', 'Yalimo'],
    timezone: 'UTC+9',
  },
  {
    iso: 'ID-PS',
    name: 'Papua Selatan',
    city: [],
    regency: ['Asmat', 'Boven Digoel', 'Mappi', 'Merauke'],
    timezone: 'UTC+9',
  },
  {
    iso: 'ID-PT',
    name: 'Papua Tengah',
    city: [],
    regency: ['Deiyai', 'Dogiyai', 'Intan Jaya', 'Mimika', 'Nabire', 'Paniai', 'Puncak', 'Puncak Jaya'],
    timezone: 'UTC+9',
  },
];
