import type { Province } from '../types';

export const provinces: Province[] = [
  {
    id: 11,
    iso: 'ID-AC',
    name: 'Aceh',
    timezone: 'UTC+7',
  },
  {
    id: 51,
    iso: 'ID-BA',
    name: 'Bali',
    timezone: 'UTC+8',
  },
  {
    id: 19,
    iso: 'ID-BB',
    name: 'Kepulauan Bangka Belitung',
    timezone: 'UTC+7',
  },
  {
    id: 36,
    iso: 'ID-BT',
    name: 'Banten',
    timezone: 'UTC+7',
  },
  {
    id: 17,
    iso: 'ID-BE',
    name: 'Bengkulu',
    timezone: 'UTC+7',
  },
  {
    id: 33,
    iso: 'ID-JT',
    name: 'Jawa Tengah',
    timezone: 'UTC+7',
  },
  {
    id: 62,
    iso: 'ID-KT',
    name: 'Kalimantan Tengah',
    timezone: 'UTC+7',
  },
  {
    id: 94,
    iso: 'ID-PT',
    name: 'Papua Tengah',
    timezone: 'UTC+9',
  },
  {
    id: 72,
    iso: 'ID-ST',
    name: 'Sulawesi Tengah',
    timezone: 'UTC+8',
  },
  {
    id: 35,
    iso: 'ID-JI',
    name: 'Jawa Timur',
    timezone: 'UTC+7',
  },
  {
    id: 64,
    iso: 'ID-KI',
    name: 'Kalimantan Timur',
    timezone: 'UTC+8',
  },
  {
    id: 53,
    iso: 'ID-NT',
    name: 'Nusa Tenggara Timur',
    timezone: 'UTC+8',
  },
  {
    id: 75,
    iso: 'ID-GO',
    name: 'Gorontalo',
    timezone: 'UTC+8',
  },
  {
    id: 95,
    iso: 'ID-PE',
    name: 'Papua Pegunungan',
    timezone: 'UTC+9',
  },
  {
    id: 15,
    iso: 'ID-JA',
    name: 'Jambi',
    timezone: 'UTC+7',
  },
  {
    id: 18,
    iso: 'ID-LA',
    name: 'Lampung',
    timezone: 'UTC+7',
  },
  {
    id: 81,
    iso: 'ID-MA',
    name: 'Maluku',
    timezone: 'UTC+9',
  },
  {
    id: 65,
    iso: 'ID-KU',
    name: 'Kalimantan Utara',
    timezone: 'UTC+8',
  },
  {
    id: 82,
    iso: 'ID-MU',
    name: 'Maluku Utara',
    timezone: 'UTC+9',
  },
  {
    id: 71,
    iso: 'ID-SA',
    name: 'Sulawesi Utara',
    timezone: 'UTC+8',
  },
  {
    id: 12,
    iso: 'ID-SU',
    name: 'Sumatera Utara',
    timezone: 'UTC+7',
  },
  {
    id: 91,
    iso: 'ID-PA',
    name: 'Papua',
    timezone: 'UTC+9',
  },
  {
    id: 14,
    iso: 'ID-RI',
    name: 'Riau',
    timezone: 'UTC+7',
  },
  {
    id: 21,
    iso: 'ID-KR',
    name: 'Kepulauan Riau',
    timezone: 'UTC+7',
  },
  {
    id: 63,
    iso: 'ID-KS',
    name: 'Kalimantan Selatan',
    timezone: 'UTC+8',
  },
  {
    id: 93,
    iso: 'ID-PS',
    name: 'Papua Selatan',
    timezone: 'UTC+9',
  },
  {
    id: 73,
    iso: 'ID-SN',
    name: 'Sulawesi Selatan',
    timezone: 'UTC+8',
  },
  {
    id: 16,
    iso: 'ID-SS',
    name: 'Sumatera Selatan',
    timezone: 'UTC+7',
  },
  {
    id: 74,
    iso: 'ID-SG',
    name: 'Sulawesi Tenggara',
    timezone: 'UTC+8',
  },
  {
    id: 96,
    iso: 'ID-PD',
    name: 'Papua Barat Daya',
    timezone: 'UTC+9',
  },
  {
    id: 31,
    iso: 'ID-JK',
    name: 'Jakarta',
    timezone: 'UTC+7',
  },
  {
    id: 32,
    iso: 'ID-JB',
    name: 'Jawa Barat',
    timezone: 'UTC+7',
  },
  {
    id: 61,
    iso: 'ID-KB',
    name: 'Kalimantan Barat',
    timezone: 'UTC+7',
  },
  {
    id: 52,
    iso: 'ID-NB',
    name: 'Nusa Tenggara Barat',
    timezone: 'UTC+8',
  },
  {
    id: 92,
    iso: 'ID-PB',
    name: 'Papua Barat',
    timezone: 'UTC+9',
  },
  {
    id: 76,
    iso: 'ID-SR',
    name: 'Sulawesi Barat',
    timezone: 'UTC+8',
  },
  {
    id: 13,
    iso: 'ID-SB',
    name: 'Sumatera Barat',
    timezone: 'UTC+7',
  },
  {
    id: 34,
    iso: 'ID-YO',
    name: 'Yogyakarta',
    timezone: 'UTC+7',
  },
];
